#############################################################################
# Makefile for building: UDP_v1
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  UDP_v1\UDP_v1.pro
# Template: app
# Command: D:\Programy\Qt\5.15.2\msvc2019_64\bin\qmake.exe -o Makefile UDP_v1\UDP_v1.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: debug
install: debug-install
uninstall: debug-uninstall
QMAKE         = D:\Programy\Qt\5.15.2\msvc2019_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = D:\Programy\Qt\5.15.2\msvc2019_64\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = D:\Programy\Qt\5.15.2\msvc2019_64\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
IDC           = idc
IDL           = midl
ZIP           = zip -r -9
DEF_FILE      = 
RES_FILE      = 
SED           = $(QMAKE) -install sed
MOVE          = move
SUBTARGETS    =  \
		debug \
		release


debug: $(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: $(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: UDP_v1\UDP_v1.pro ..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\spec_pre.prf \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\common\angle.conf \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\common\windows-desktop.conf \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\win32\windows_vulkan_sdk.prf \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\common\windows-vulkan.conf \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\common\msvc-desktop.conf \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\qconfig.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3danimation.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3danimation_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dcore.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dcore_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dextras.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dextras_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dinput.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dinput_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dlogic.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dlogic_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquick.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquick_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickanimation.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickanimation_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickextras.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickextras_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickinput.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickrender.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickscene2d.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickscene2d_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3drender.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3drender_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_accessibility_support_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_axbase.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_axbase_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_axcontainer.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_axcontainer_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_axserver.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_axserver_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_bluetooth.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_bluetooth_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_bodymovin_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_bootstrap_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_charts.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_charts_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_concurrent.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_concurrent_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_core.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_core_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_datavisualization.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_datavisualization_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_dbus.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_dbus_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_designer.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_designer_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_designercomponents_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_edid_support_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_egl_support_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_fb_support_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_fontdatabase_support_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_gamepad.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_gamepad_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_gui.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_gui_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_help.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_help_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_location.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_location_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_multimedia.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_multimedia_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_multimediawidgets.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_network.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_network_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_networkauth.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_networkauth_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_nfc.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_nfc_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_opengl.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_opengl_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_openglextensions.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_openglextensions_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_platformcompositor_support_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_positioning.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_positioning_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_positioningquick.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_positioningquick_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_printsupport.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_printsupport_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_purchasing.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_purchasing_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qml.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qml_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmldebug_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmlmodels.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmlmodels_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmltest.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmltest_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmlworkerscript.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmlworkerscript_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3d.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3d_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dassetimport.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dassetimport_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3drender.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3drender_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3druntimerender.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3druntimerender_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dutils.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dutils_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quickparticles_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quickshapes_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quicktemplates2.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quickwidgets.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_remoteobjects.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_remoteobjects_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_repparser.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_repparser_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_script.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_script_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_scripttools.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_scripttools_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_scxml.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_scxml_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_sensors.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_sensors_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_serialbus.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_serialbus_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_serialport.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_serialport_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_sql.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_sql_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_svg.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_svg_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_testlib.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_testlib_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_texttospeech.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_texttospeech_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_theme_support_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_uiplugin.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_uitools.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_uitools_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_virtualkeyboard.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_virtualkeyboard_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_vulkan_support_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webchannel.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webchannel_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webengine.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webengine_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webenginecore.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webenginecore_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webenginecoreheaders_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webenginewidgets.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webenginewidgets_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_websockets.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_websockets_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webview.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webview_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_widgets.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_widgets_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_windowsuiautomation_support_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_winextras.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_winextras_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_xml.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_xml_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_xmlpatterns.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_zlib_private.pri \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\qt_functions.prf \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\qt_config.prf \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\win32-msvc\qmake.conf \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\spec_post.prf \
		.qmake.stash \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\exclusive_builds.prf \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\common\msvc-version.conf \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\toolchain.prf \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\default_pre.prf \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\win32\default_pre.prf \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\resolve_config.prf \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\exclusive_builds_post.prf \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\default_post.prf \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\qml_debug.prf \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\precompile_header.prf \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\warn_on.prf \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\qt.prf \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\resources_functions.prf \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\resources.prf \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\moc.prf \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\win32\opengl.prf \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\uic.prf \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\qmake_use.prf \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\file_copies.prf \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\win32\windows.prf \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\testcase_targets.prf \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\exceptions.prf \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\yacc.prf \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\lex.prf \
		UDP_v1\UDP_v1.pro \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\lib\Qt5Widgets.prl \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\lib\Qt5Gui.prl \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\lib\Qt5Network.prl \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\lib\Qt5SerialPort.prl \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\lib\Qt5Core.prl \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\lib\qtmain.prl \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\build_pass.prf \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\lib\Qt5Widgetsd.prl \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\lib\Qt5Guid.prl \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\lib\Qt5Networkd.prl \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\lib\Qt5SerialPortd.prl \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\lib\Qt5Cored.prl \
		..\..\..\Programy\Qt\5.15.2\msvc2019_64\lib\qtmaind.prl
	$(QMAKE) -o Makefile UDP_v1\UDP_v1.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\spec_pre.prf:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\common\angle.conf:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\common\windows-desktop.conf:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\win32\windows_vulkan_sdk.prf:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\common\windows-vulkan.conf:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\common\msvc-desktop.conf:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\qconfig.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3danimation.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3danimation_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dcore.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dcore_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dextras.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dextras_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dinput.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dinput_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dlogic.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dlogic_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquick.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquick_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickanimation.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickanimation_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickextras.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickextras_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickinput.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickinput_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickrender.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickrender_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickscene2d.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3dquickscene2d_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3drender.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_3drender_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_accessibility_support_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_axbase.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_axbase_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_axcontainer.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_axcontainer_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_axserver.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_axserver_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_bluetooth.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_bluetooth_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_bodymovin_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_bootstrap_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_charts.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_charts_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_concurrent.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_concurrent_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_core.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_core_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_datavisualization.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_datavisualization_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_dbus.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_dbus_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_designer.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_designer_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_designercomponents_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_edid_support_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_egl_support_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_fb_support_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_fontdatabase_support_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_gamepad.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_gamepad_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_gui.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_gui_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_help.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_help_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_location.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_location_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_multimedia.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_multimedia_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_multimediawidgets.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_network.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_network_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_networkauth.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_networkauth_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_nfc.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_nfc_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_opengl.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_opengl_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_openglextensions.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_openglextensions_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_packetprotocol_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_platformcompositor_support_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_positioning.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_positioning_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_positioningquick.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_positioningquick_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_printsupport.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_printsupport_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_purchasing.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_purchasing_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qml.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qml_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmldebug_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmldevtools_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmlmodels.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmlmodels_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmltest.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmltest_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmlworkerscript.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qmlworkerscript_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3d.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3d_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dassetimport.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dassetimport_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3drender.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3drender_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3druntimerender.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3druntimerender_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dutils.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick3dutils_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quick_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quickparticles_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quickshapes_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quicktemplates2.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quickwidgets.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_quickwidgets_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_remoteobjects.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_remoteobjects_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_repparser.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_repparser_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_script.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_script_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_scripttools.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_scripttools_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_scxml.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_scxml_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_sensors.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_sensors_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_serialbus.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_serialbus_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_serialport.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_serialport_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_sql.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_sql_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_svg.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_svg_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_testlib.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_testlib_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_texttospeech.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_texttospeech_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_theme_support_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_uiplugin.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_uitools.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_uitools_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_virtualkeyboard.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_virtualkeyboard_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_vulkan_support_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webchannel.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webchannel_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webengine.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webengine_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webenginecore.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webenginecore_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webenginecoreheaders_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webenginewidgets.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webenginewidgets_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_websockets.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_websockets_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webview.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_webview_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_widgets.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_widgets_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_windowsuiautomation_support_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_winextras.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_winextras_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_xml.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_xml_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_xmlpatterns.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\modules\qt_lib_zlib_private.pri:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\qt_functions.prf:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\qt_config.prf:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\win32-msvc\qmake.conf:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\spec_post.prf:
.qmake.stash:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\exclusive_builds.prf:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\common\msvc-version.conf:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\toolchain.prf:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\default_pre.prf:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\win32\default_pre.prf:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\resolve_config.prf:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\exclusive_builds_post.prf:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\default_post.prf:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\qml_debug.prf:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\precompile_header.prf:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\warn_on.prf:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\qt.prf:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\resources_functions.prf:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\resources.prf:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\moc.prf:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\win32\opengl.prf:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\uic.prf:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\qmake_use.prf:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\file_copies.prf:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\win32\windows.prf:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\testcase_targets.prf:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\exceptions.prf:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\yacc.prf:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\lex.prf:
UDP_v1\UDP_v1.pro:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\lib\Qt5Widgets.prl:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\lib\Qt5Gui.prl:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\lib\Qt5Network.prl:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\lib\Qt5SerialPort.prl:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\lib\Qt5Core.prl:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\lib\qtmain.prl:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\mkspecs\features\build_pass.prf:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\lib\Qt5Widgetsd.prl:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\lib\Qt5Guid.prl:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\lib\Qt5Networkd.prl:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\lib\Qt5SerialPortd.prl:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\lib\Qt5Cored.prl:
..\..\..\Programy\Qt\5.15.2\msvc2019_64\lib\qtmaind.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile UDP_v1\UDP_v1.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"

qmake_all: FORCE

make_first: debug-make_first release-make_first  FORCE
all: debug-all release-all  FORCE
clean: debug-clean release-clean  FORCE
	-$(DEL_FILE) UDP_v1.vc.pdb
	-$(DEL_FILE) UDP_v1.ilk
	-$(DEL_FILE) UDP_v1.idb
distclean: debug-distclean release-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash UDP_v1.pdb

debug-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocclean
release-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocclean
mocclean: debug-mocclean release-mocclean

debug-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocables
release-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocables
mocables: debug-mocables release-mocables

check: first

benchmark: first
FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
